export const BASE_URL = 'http://rutor.info'
export const BASE_SERCH_URL = 'http://rutor.info/search'
export const MAGNET_KEY = 'magnet:?xt'
export const MAGENT_SPLIT = 'urn:btih:'
export const IMDB_KEY = 'a0118505cee9f6d57692656811f5a3ac'
export const IMDB_API_URL = 'https://api.themoviedb.org/3'
