export const movieMock = JSON.stringify({
  title: 'Индиана Джонс и последний крестовый поход',
  description:
    'Третья часть невероятных похождений прославленного археолога и искателя приключений Индианы Джонса. На этот раз бесстрашный Индиана разыскивает самую таинственную реликвию в истории человечества — Святой Грааль. В этом археологу помогает его отец — профессор Джонс старший.Теперь под бдительным оком своего отца и при помощи своих верных талисманов, неизменной шляпы и хлыста, Индиане предстоит совершить много благородных подвигов и потрясающих открытий. В новых странствиях храброму археологу доведется добыть чашу, которую держал в руках Иисус Христос и получить автограф… самого Адольфа Гитлера.',
  year: '1989',
  poster:
    'http://i40.fastpic.ru/big/2012/0914/7a/5a34475f8ae19439109277b2070bb87a.png',
  trailer: 'https://www.youtube.com/watch?v=GIrpRBVnOu4&ab_channel=GoodMoments',
  runtime: '02:06:53',
  ratingImdb: '8.2',
  imdbId: 'tt0097576',
  rated: 'PG13',
  actors: [
    'Харрисон',
    'Форд',
    '(Indiana',
    'Jones),',
    'Шон',
    'Коннери',
    '(Professor',
    'Henry',
    'Jones),',
    'Денхолм',
    'Эллиот',
    '(Marcus',
    'Brody),',
    'Элисон',
    'Дуди',
    '(Dr.',
    'Elsa',
    'Schneider),',
    'Джон',
    'Рис-Дэвис',
    '(Sallah),',
    'Джулиан',
    'Гловер',
    '(Walter',
    'Donovan),',
    'Ривер',
    'Феникс',
    '(Young',
    'Indy),',
    'Майкл',
    'Бирн',
    '(General',
    'Vogel),',
    'Кеворк',
    'Маликян',
    '(Kazim),',
    'Роберт',
    'Эддисон',
    '(Grail',
    'Knight),',
    'Ричард',
    'Янг',
    '(Fedora),',
    'Алексей',
    'Сейл',
    '(Sultan)',
  ],
  ganre: ['боевик', 'приключения'],
  director: ['Стивен Спилберг / Steven Spielberg'],
  magnet: '847cebf80488fe3f1d6515ec1be2ddf542c16f44',
  fileName:
    'Indiana.Dzhons.I.Poslednii.Krestovyi.Pohod.1989.RUS.BDRip.XviD.AC3.-HQ-ViDEO.avi',
  sourceUrl:
    'http://rutor.info/torrent/442402/indiana-dzhons-i-poslednij-krestovyj-pohod_indiana-jones-and-the-last-crusade-1989-bdrip-ot-hq-video-p-p2-a',
})
